import type { Metadata } from "next";
import SideBar from "./_components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="xl:px-32">
      <div className="w-full flex flex-wrap">
        <div className="hidden md:block w-full md:w-3/12 sticky top-0 h-screen p-4">
          <SideBar />
        </div>
        <div className="w-full md:w-9/12 p-4">
          <div>{children}</div>
        </div>
      </div>
    </main>
  );
}
