import type { Metadata } from "next";
import SideBar from "./_components/sidebar";
// import Bowls from "./_components/bowl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="px-4 lg:px-32">
      <div className="w-full flex flex-wrap">
        <div className="w-full md:w-3/12">
          <SideBar />
        </div>
        <div className="w-full md:w-9/12 h-screen overflow-y-auto">
          <div>{children}</div>
        </div>
        {/* <div className="w-full md:w-3/12">
          <Bowls />
        </div> */}
      </div>
    </main>
  );
}
